package main

import (
	_ "github.com/hamed-lohi/user-manage/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/hamed-lohi/user-manage/initialize"
)

// @title Swagger Example API
// @version 1.3
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {

	initialize.InitializeWebServer()

}
