package main

import (
	"github.com/labstack/gommon/log"

	echoSwagger "github.com/swaggo/echo-swagger"

	"github.com/hamed-lohi/user-management/db"
	_ "github.com/hamed-lohi/user-management/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/hamed-lohi/user-management/handler"
	"github.com/hamed-lohi/user-management/middleware"
	"github.com/hamed-lohi/user-management/store"
)

// @title Swagger Example API
// @version 1.3
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {

	e := middleware.NewEcho()
	e.Logger.SetLevel(log.DEBUG)

	// // Group level middleware
	// g := e.Group("/admin")
	// g.Use(middleware.BasicAuth(func(username, password string, c echo.Context) (bool, error) {
	// if username == "joe" && password == "secret" {
	// 	return true, nil
	// }
	// return false, nil
	// }))

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := e.Group("/api")

	cl := db.New()
	defer cl.Dispose()
	cl.Seed()
	coll := cl.Database("user_management_db").Collection("users")

	us := store.NewUserStore(coll)
	h := handler.NewHandler(us)
	h.Register(v1)
	e.Logger.Fatal(e.Start("127.0.0.1:8585"))

}
